### ISSUE TITLE
Load file inside sidebar

### ISSUE THREAD

**Issue by htwmehdi** [Turbo87/leaflet-sidebar#42]
Hello,

How can i load a file and insert it into the sidebar div ?
I have many markers, and each one have a seperate file with datas to be shown in the sidebar, i have tried the .setContent function, but i do have a php function that runs a query that must be displayed in the sidebar.

thank you

**Comment by zedd45** [comment]
The loading of the file contents and the displaying are two different concerns: 

1. you can use [`fetch`](https://github.com/github/fetch) or `ajax` ([jQuery flavored](http://api.jquery.com/jquery.ajax/) or [otherwise](https://developer.mozilla.org/en-US/docs/AJAX/Getting_Started)) to make a request to the server that returns the file contents.   
1. `.setContent` method takes a `String` and sets the content of the sidebar to that string

assuming
```
var sidebar = L.control.sidebar( 
   //...
);
```

Therefore, once you have loaded the string / text you want from PHP via your desired method, you can just call `sidebar.setContent(myStringFromTheSever)`
