### ISSUE TITLE
Using plugin in R Leaflet

### ISSUE THREAD

**Issue by MichelAKroeze** [Turbo87/leaflet-sidebar#64]
I cannot get the plugin to work in R.
I have unsuccessfully tried to follow this guide: https://gist.github.com/timelyportfolio/8f6c8cc27597466351ad377e6774c30f#using-arbitrary-leaflet-js-plugins-with-leaflet-for-r

This is where I'm currently at:
```
`sidebarPlugin <- htmlDependency("leaflet-sidebar", "0.2.0",
                                src = c(href = "https://github.com/Turbo87/leaflet-sidebar.git"),
                                script = "src/L.Control.Sidebar.js")
```

```
registerPlugin <- function(map, plugin) {
  map$dependencies <- c(map$dependencies, list(plugin))
  map
}
```

```
testLeaflet <- leaflet() %>%
  addTiles %>%
  registerPlugin(sidebarPlugin)%>%
  onRender("function(el, x) {
      var sidebar = L.control.sidebar('sidebar', {
      position: 'left'}).addTo(this);
      map.addControl(sidebar).addTo(this);
      sidebar.show().addTo(this);
  }")
```
`
Does anyone have any guidance on what I should do?

**Comment by zedd45** [comment]
I'm not familiar with `R`.  Do you get a JS error / stack trace? Is there a minimal repo we could look at?

**Comment by nelsonis** [comment]
You are close but the problem arises because of the source url you use to construct the `htmlDependency`

The `htmlDependency` function expects a url that contains a JavaScript function in application/javascript format. The Url you specified, which is [https://github.com/Turbo87/leaflet-sidebar.git/src/L.Control.Sidebar.js](https://github.com/Turbo87/leaflet-sidebar.git/src/L.Control.Sidebar.js) does not contain an actual JavaScript but instead responds with `{"error":"Not Found"}`

Luckily there is a online service which provides most js libraries available through npm and github in application/javascript format, namely [jsdelivr ](https://www.jsdelivr.com). As a matter of fact, the guide you referenced uses this service to load `leaflet.esri` and add it to a leaflet map.

The js files of [leaflet-sidebar](https://www.jsdelivr.com/package/npm/leaflet-sidebar) can also be found on on jsdelivr and the site is pretty self explanatory.  So in your case the corrected `htmlDependency` should look something like this.

```
htmlDependency("leaflet-sidebar", "0.2.0",
                src = c(href = 'https://cdn.jsdelivr.net/npm/leaflet-sidebar@0.2.0/'),
                script = 'src/leaflet-sidebar.js', stylesheet = 'src/leaflet-sidebar.css')
```

**Comment by zedd45** [comment]
I have since used R. I will close this for now, as it has been inactive, and @nelsonis seems to have supplied a working solution.  Please feel free to re-open if necessary.
