### ISSUE TITLE
When get bounds center object to map look like is not center 

### ISSUE THREAD

**Issue by ridwanskaterock** [Turbo87/leaflet-sidebar#82]
![image](https://user-images.githubusercontent.com/9270445/117689077-9b87e880-b1e3-11eb-8206-14ba074d88bf.png)

how not to count the sidebar as part of the map?

**Comment by zedd45** [comment]
The sidebar appears over the map while it is open (it’s a “fly out”). 

This is by design, but you could try offsetting the center by the size of the fly out. 

Note there is a newer version of the library as well. Although I am not sure it would fix this problem. Please see the readme for more information.
